# -*- coding: utf-8 -*-
"""Uji Coba Library107

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FRzMv0H0j6kK_EDnAR9Xq49FGVcbtNXR
"""

import raihan107

A = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

B = [
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
]

hasil_tambah = raihan107.tambah_matriks(A, B)
hasil_kurang = raihan107.kurang_matriks(A, B)
hasil_kali = raihan107.kali_matriks(A, B)

print("Hasil Penjumlahan:")
for baris in hasil_tambah:
    print(baris)

print("\nHasil Pengurangan:")
for baris in hasil_kurang:
    print(baris)

print("\nHasil Perkalian:")
for baris in hasil_kali:
    print(baris)